<ul>
    <li>
        <a href="<?php echo $this->url(array('page' => 'aboutus'),'static-content'); ?>">
        <?php echo $this->translate('static_content_aboutUs')?>
        </a>
    </li>
    <li>
        <a href="<?php echo $this->url(array('page' => 'help'),'static-content'); ?>">
        <?php echo $this->translate('static_content_help')?>
        </a>
    </li> 
    <li>
        <a href="<?php echo $this->url(array('page' => 'terms'),'static-content'); ?>">
        <?php echo $this->translate('static_content_terms')?>
        </a>
    </li> 
    <li>
        <a href="<?php echo $this->url(array('page' => 'privacy'),'static-content'); ?>">
        <?php echo $this->translate('static_content_privacy')?>
        </a>
    </li>
    <li>
        <a href="<?php echo $this->url(array('page' => 'languages'),'static-content'); ?>">
        <?php echo $this->translate('static_content_languages')?>
        </a>
    </li>
    <li>
        2012 @voilamylife.com
    </li>
</ul>

    