<div data-role="page" id="<?php echo $this->id ? $this->id : '' ?>"><!-- page -->
    <?php echo $this->partial('partial/_header.mobile.phtml',array('title' => $this->title,'buttonLeft' => $this->buttonLeft,'buttonRight'=>$this->buttonRight)); ?>
    <div data-role="content">	
        <?php echo $this->content; ?>
    </div><!-- /content -->
    <?php echo ($this->footer)? $this->partial('partial/'.$this->footer.'.phtml',array('active' => $this->active)): ''?>
</div><!-- end of page -->

    