<ul data-role="listview" data-inset="true">
    <!-- only the submenu for the options -->
<?php 
    $options = array();
    foreach ($this->container as $page) 
    {
        foreach ($page->getPages() as $subPage)
        {
            $subPage->setCustomHtmlAttribs(array('data-ajax' => 'false'));
            if (isset($options[$subPage->getOrder()]))
            {
                $options[] ='    <li>'.$this->navigation()->menu()->htmlify($subPage).'</li>'."\n";
            }
            else
            {
                $options[$subPage->getOrder()] = '    <li>'.$this->navigation()->menu()->htmlify($subPage).'</li>'."\n";
            }
        }
    }
    ksort($options);
    foreach ($options as $option)
    {
        echo $option;
    } ?>
</ul>

    