<table class="table table-striped table-bordered table-hover table-condensed">
    <caption><?php echo ucfirst(Pepit_Inflector::pluralize($this->generalizedItemType)) ;?></caption>
    <thead>
        <tr>
            <th><?php echo ucfirst($this->generalizedItemType) ;?> Name</th>
            <th><?php echo ucfirst($this->generalizedItemType) ;?> Id</th>
            <th><?php echo ucfirst($this->generalizedItemRowType) ;?> number</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>-</td> 
            <td>-</td> 
            <td><?php echo $this->generalizedItemRowsCounts['total'];?></td> 
            <td>
                <a href="<?php echo $this->url(array('controller' => strtolower($this->generalizedItemType),'action'=>'create'),'backend');?>" >
                    Create new <?php echo $this->generalizedItemType ;?>
                </a>
            </td> 
        </tr> 
<?php foreach ($this->generalizedItems as $generalizedItem) : 
    $metaCategory = (property_exists($generalizedItem,'categories') 
        && $generalizedItem->categories->count()>0);?>
        <tr>
            <td><?php echo ucfirst($generalizedItem->name).(($metaCategory) ? ' (metaCategory)':'');?></td> 
            <td><?php echo $generalizedItem->id;?></td> 
            <td><?php if (array_key_exists($generalizedItem->name,$this->generalizedItemRowsCounts)) : echo $this->generalizedItemRowsCounts[$generalizedItem->name] ; else : echo '0'; endif;?></td> 
            <td>
                <a href="<?php echo $this->url(array('controller'=> strtolower($this->generalizedItemType),'action'=>'edit','entityId' => $generalizedItem->id),'backend');?>">
                    Edit
                </a>
                <?php if ($this->checkCategoryDeletePossible($generalizedItem->id,$this->entityManager())) :?>
                    <a href="<?php echo $this->url(array('controller'=> strtolower($this->generalizedItemType),'action'=>'delete','entityId' => $generalizedItem->id),'backend');?>">
                        Delete
                    </a>
                <?php endif; ?>
                <?php if (!$metaCategory) :?> <a href="<?php echo $this->url(array('controller'=> strtolower($this->generalizedItemRowType),'action'=>'create','containerId' => $generalizedItem->id),'event');?>">
                    Add row
                </a>
                <?php endif;?>
            </td> 
        </tr> 
<?php endforeach;?>        
    </tbody>
</table>





