<div class="row-fluid">
    <div class="span9">
        <div class="span4">
            <div class="category-button btn btn-large btn-primary btn-block">balbla</div>
        </div>
        <div class="category-button span4">
            <div class="btn btn-large btn-primary btn-block">balbla</div>
            
        </div>
        <div class="span4">
            <div id ="by" class="category-button btn btn-large btn-primary btn-block">balbla</div>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span9">
        <div class="span4">
            <div id ="by" class="category-button btn btn-large btn-primary btn-block">balbla</div>
        </div>
        <div class="span4">
            <div id ="by" class="category-button btn btn-large btn-primary btn-block">balbla</div>
        </div>
        <div class="span4">
            <div id ="by" class="category-button btn btn-large btn-primary btn-block">balbla</div>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span9">
<div class="span4">
    <div id ="by" class="category-button btn btn-large btn-primary btn-block">balbla</div>
</div>
<div class="span4">
    <div id ="by" class="category-button btn btn-large btn-primary btn-block">balbla</div>
</div>
<div class="span4">
    <div id ="by" class="category-button btn btn-large btn-primary btn-block">balbla</div>
</div>
</div>
</div>

