<?php 
    $singleCat = $metaCat = $cat = [];
    
    $config = Zend_Registry::get('config');
    $imgPath = $config->public->images->icon->category->path; 
    foreach ($this->container as $page) 
    {
        foreach ($page->getPages() as $subPage)
        {
            if ($subPage->isMeta)
            {
                $metaCat[] = $cat[] = $this->categoryListLine($subPage,$imgPath,true,false,'arrow-r','<img src="/images/icons/nav_bar/photos.png" style="width:15px;height:15px;">');
                
            }
            else
            {
                $singleCat[] = $cat[] = $this->categoryListLine($subPage,$imgPath);
            }
            
        }
    }
    
    //sorting lines of categories, the first being the most used
    //(with the most events)
    usort($singleCat,$this->listCategories()->compEvents);
    usort($metaCat,$this->listCategories()->compEvents);
    usort($cat,$this->listCategories()->compEvents);
    
    // some lines are show, the rest being in a collapsible set
    $lineShown = $config->categories->list->lines->show;
?>

<ul id="list-singleCat" data-role="listview" data-filter="true" data-filter-placeholder="<?php echo $this->translate('searchbar_search_categories'); ?>" data-filter-theme="d">
    <?php foreach ($cat as $option): echo $option['render'] ; endforeach;?>
</ul>

