<?php 
    $singleCat = $metaCat = $cat = [];
    
    $config = Zend_Registry::get('config');
    
    $imgPath = $config->public->images->icon->category->path;
    foreach ($this->container as $page) 
    {
        foreach ($page->getPages() as $subPage)
        {
            $options = [
                'categoryName'  => $subPage->getLabel(),
                'categoryId'    => $subPage->categoryId,
                'href'          => $subPage->getHref(),
                'nbEvents'      => count($subPage->events),
                'bubbleCount'   => true,
                
            ];
            
            if ($subPage->getLabel() === 'category_all')
            {
                $options['imgAttribs'] = [
                    'src'       => '/images/icons/other/allEvents.jpg',
                    'class'     => 'ui-li-icon',
                    'style'     => 'min-width: 30px;'
                ];
            }
            
            if ($this->imgFileExists($src = sprintf($imgPath,
                ucfirst(preg_replace('#category_#','',$options['categoryName'])))))
            {
                $options['imgAttribs'] = ['src' => $src];
            }
            
            if ($subPage->isMeta)
            {
                $options['subTitle'] = '<img src="/images/icons/nav_bar/photos.png" style="width:15px;height:15px;">';
                $metaCat[] = $cat[] = $this->categoryListLine($options);
                
            }
            else
            {
                $singleCat[] = $cat[] = $this->categoryListLine($options);
            }
            
        }
    }
    
    //sorting lines of categories, the first being the most used
    //(with the most events)
    usort($singleCat,$this->listCategories()->compEvents);
    usort($metaCat,$this->listCategories()->compEvents);
    usort($cat,$this->listCategories()->compEvents);
    
    $lineShown = $config->categories->list->lines->show;
?>

<ul id="list-singleCat" data-role="listview" data-filter="true" data-filter-placeholder="<?php echo $this->translate('searchbar_search_categories'); ?>" data-filter-theme="d">
    <?php foreach ($cat as $option): echo $option['render'] ; endforeach;?>
</ul>

