
<?php
    $list = '';
    $filterMonth = new Pepit_Filter_DateTimeToDateForm(array('date_format' => Zend_Date::MONTH_NAME));
    $filterYear = new Pepit_Filter_DateTimeToDateForm(array('date_format' => Zend_Date::YEAR));
    
    $month = null;
    $year = null;
    $eventsForFront = [];
    foreach ($this->events as $event)
    {
        //we put a divider each month
        if (!($filterMonth->filter($event->date) === $month &&
                $filterYear->filter($event->date) === $year))
        {
            $month = $filterMonth->filter($event->date);
            $year = $filterYear->filter($event->date);
            $list .= '<li data-role="list-divider">'.$month.' '.$year.'</li>';
        }
        $list .= $this->event($event)->eventLine();
        $eventsForFront[]  = $this->event($event)->eventForFront();
        
    }
    
    $this->inlineScript()->setAllowArbitraryAttributes('true')
            ->offsetSetScript(
                    102,
                    'var lastEvents = '.Zend_Json::encode($eventsForFront).';'
                    ,'text/javascript',
                    ['noescape'=>'true','id' => 'last-events-list']
            );
?>
        
<ul data-role="listview" id="last-events-list-view">    
    <?php echo $list; ?>
</ul>