<div data-role="controlgroup" data-type="horizontal">
    <a href="#choice-param" data-role="button" data-rel="popup" data-position-to="window">Bar</a>
    <a href="#choice-param" data-role="button" data-rel="popup" data-position-to="window">Pie</a>
    <a href="#choice-param" data-role="button" data-rel="popup" data-position-to="window">Data</a>
</div>
<div data-role="popup" id="choice-param" data-theme="a">
	<ul data-role="listview" data-inset="true" style="min-width:210px;" data-theme="b">
                <li data-role="" data-theme="a">Parameter</li>
                <li><a href="">Frequency</a></li>
                <li><a href="">Price</a></li>
        </ul>
</div>

<?php 
    
    $form = $this->event($this->events[0])->getForm();
    foreach ($form->getElements() as $formElement)
    {
        echo $this->visualRep($formElement,$this->events);
    }





