<?php $this->inlineScript()->offsetSetFile(180,'/js/lib/simple-plugin/jquery.sudoSlider.js');
      $this->inlineScript()->offsetSetFile(181,'/js/lib/simple-plugin/jquery.touchSwipe-1.2.4.js');
      $this->headLink()->prependStylesheet('/css/simple-plugin.css'); ?>

<div data-role="controlgroup" data-type="horizontal">
    <a href="#choice-param" data-role="button" data-rel="popup" data-position-to="window">Bar</a>
    <a href="#choice-param" data-role="button" data-rel="popup" data-position-to="window">Pie</a>
    <a href="#choice-param" data-role="button" data-rel="popup" data-position-to="window">Data</a>
</div>
<div data-role="popup" id="choice-param" data-theme="a">
	<ul data-role="listview" data-inset="true" style="min-width:210px;" data-theme="b">
                <li data-role="" data-theme="a">Parameter</li>
                <li><a href="">Frequency</a></li>
                <li><a href="">Price</a></li>
        </ul>
</div>
<div id="container">
	<div style="position:relative;">
            <div id="containerslider">
                    <div id="slider">
                            <ul>
                            <?php 

                                $form = $this->event($this->events[0])->getForm();
                                $commonElement=['date','location','image','tags','persons'];
                                foreach ($form->getElements() as $formElement)
                                {
                                    //if no category is choosen show only fot the common properties
                                    if ((!$this->all || in_array($formElement->getId(),$commonElement)))
                                    {
                                        echo $this->visualRep($formElement,$this->events,['wrapper' => 'li','htmlTag' => 'div']);
                                    }
                                }
                            ?>			
                            </ul>
                    </div>
            </div>
	</div>
	<a href="#" class="previousclass" >Previous</a> - <a href="#" class="nextclass" >Next</a></p>
</div>