<div data-role="page" id="<?php echo $this->id ? $this->id : '' ?>"><!-- page -->
    <div data-role="header" data-position="fixed" data-id="header" data-tap-toggle="false">
        <?php echo $this->buttonHeader($this->buttonLeft,'left') ?>
        <h1><?php echo $this->title ;?></h1>
        <?php echo $this->buttonHeader($this->buttonRight,'right') ?>
    </div><!-- /header -->
    <div data-role="content">	
        <div data-role="controlgroup" data-mini="true" data-type="horizontal">
            <?php echo $this->buttons; ?>
        </div>
        
        <?php echo $this->graph; ?>
    </div><!-- /content -->
    <?php echo $this->footer ?>
</div><!-- end of page -->