
<?php
    $list = '';
    $monthPrev = null;
    $yearPrev = null;
    
    $eventsForFront = [];
    foreach ($this->events as $event)
    {
        $eventHelper = $this->event();
        $eventHelper->setEvent($event);
        
        $date = $event->date;
        $month = $date->format('n');
        $year = $date->format('Y');

        //we put a divider each month
        if (!($month === $monthPrev && $year === $yearPrev))
        {
            $monthPrev = $month;
            $yearPrev = $year;
            
            $list .= '<li data-role="list-divider">'
                    .$eventHelper->getLocalizedMonth()['format']['wide'][$date->format('n')]
                    .' '.$year.'</li>';
        }
        $list .= $eventHelper->eventLine();
        $eventsForFront[]  = $eventHelper->eventForFront();
        
    }
    
    $this->inlineScript()->setAllowArbitraryAttributes('true')
            ->offsetSetScript(
                    102,
                    'var lastEvents = '.Zend_Json::encode($eventsForFront).';'
                    ,'text/javascript',
                    ['noescape'=>'true','id' => 'last-events-list']
            );
?>
        
<ul data-role="listview" id="last-events-list-view">    
    <?php echo $list; ?>
</ul>