<?php   $this->headScript()->offsetSetFile(100,'https://www.google.com/jsapi');
        
        $this->inlineScript()->offsetSetFile(200,'/js/lib/jquery_mobile/jqm.autoComplete.js');
        $this->inlineScript()->offsetSetFile(30,"http://maps.googleapis.com/maps/api/js?key=AIzaSyCF7ZgOuhe3sg_c1J0F7hpuace2NAv-DVk&sensor=false&libraries=places,geometry");
        $this->inlineScript()->offsetSetFile(40,'/js/lib/underscore.js');
        $this->inlineScript()->offsetSetFile(50,'/js/lib/backbone.js');
            
        $this->inlineScript()->offsetSetFile(150,'/js/mvc/models//event-save/tag.js');
        $this->inlineScript()->offsetSetFile(151,'/js/mvc/views/event-save/tagView.js');
        $this->inlineScript()->offsetSetFile(152,'/js/mvc/models/event-save/input.js');
        $this->inlineScript()->offsetSetFile(153,'/js/mvc/models/event-save/tags.js');
        $this->inlineScript()->offsetSetFile(154,'/js/mvc/views/event-save/inputView.js');
        $this->inlineScript()->offsetSetFile(155,'/js/mvc/views/event-save/subformView.js');
        $this->inlineScript()->offsetSetFile(156,'/js/mvc/views/event-save/hiddenFormView.js');
        $this->inlineScript()->offsetSetFile(157,'/js/mvc/views/event-save/hiddenTagSimpleFormView.js');
        
        $this->inlineScript()->offsetSetFile(158,'/js/mvc/utils/close.js');
        $this->inlineScript()->offsetSetFile(140,'/js/mvc/utils/mylife.js');
        
        $this->inlineScript()->offsetSetFile(159,'/js/mvc/views/popupView.js');
        $this->inlineScript()->offsetSetFile(160,'/js/mvc/views/gpsButtonView.js');
        $this->inlineScript()->offsetSetFile(170,'/js/mvc/views/event-save/singleItemPageView.js');
        $this->inlineScript()->offsetSetFile(171,'/js/mvc/views/event-save/saveEventPageBodyView.js');
        
        ?>

<form enctype="multipart/form-data" id="add_event" data-ajax="false" action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>">
<?php 
    echo $this->form->categoryId;
    echo $this->form->date;
    $this->form->removeElement('categoryId');
    
    echo $this->form->getElement($this->submit);
    $this->form->removeElement($this->submit);
    
    $date = new Zend_Date($this->form->getElement('date')->getValue(),Pepit_Date::MYSQL_DATE);
    $dateShow = $date->toString(Zend_Date::DATE_MEDIUM);
    $this->form->removeElement('date');
    
    $name = 'category_'.$this->category->name ;
   
    foreach ($this->form->getElements() as $formElement)
    {
        //take only the item parameters, except date element
        $propertyName = $formElement->getAttrib('data-property-name');
        
        if ($propertyName)
        {
            echo $this->partial('partial/_pageEventForm.phtml', array(
                'id'             => $propertyName.'_page',
                'propertyName'   => $propertyName,
                'class'          => 'item_page',
                'title'          => ucfirst($this->translate($name)),
                'date'           => $dateShow,
                'form'           => $this->form,
                'content'        => $this->partial(
                        'partial/_formElement.phtml',
                        array('formElement'=> $formElement)),
            )) ;
            
            //adding another formular for item group elements 
            //(element with more than one field
            
            if ($formElement->getAttrib('data-item-type') 
                === \ZC\Entity\GeneralizedItem::GENERALIZED_ITEM_ITEM_GROUP)
            {
                echo $this->partial('partial/_pageItemGroupForm.phtml', array(
                'id'             => $propertyName.'_itemGroup_form_page',
                'propertyName'   => $propertyName,
                'class'          => 'item_group_form_page',
                'title'          => ucfirst($this->translate($name)),
                'date'           => $dateShow,
                'form'           => $this->form,
                'content'        => $this->action('create','itemgrouprow','events',array(
                                    'containerId' => $formElement->getAttrib('itemGroupId'))),
                ));
            }
        }
    }
?>
</form>