<div class="ui-body ui-body-d">
    <h1 id="title-description" class="title_guide"><?php echo $this->translate('Save, remember and enjoy.')?></h1>
    <h2 id="subtitle-description" class="title_guide"><?php echo $this->translate('With Mylife, you can:'); ?></h2>
    <h2 class="title-function"><?php echo $this->translate('Visualize')?></h2>
    <ul data-role="listview" data-inset="true">
        <li>
            <button data-theme="b" data-corners="true" data-iconpos="notext" data-inline="true" data-icon="mylife-home"></button>
            <button data-theme="b" data-corners="true" data-iconpos="notext" data-inline="true" data-icon="mylife-calendar"></button>
            <button data-theme="b" data-corners="true" data-iconpos="notext" data-inline="true" data-icon="mylife-graphs"></button>
            <?php echo $this->translate('Every category has several possible visualizations')?></li>
        <li><?php echo $this->translate('Get dedicated visual for each family of events')?></li>
        <li><?php echo $this->translate('Choose the events to see thanks to your own tags')?></li>
    </ul>
    
    <h2 class="title-function"><?php echo $this->translate('Save')?></h2>
    <ul data-role="listview" data-inset="true">
        <li><button data-theme="b" data-corners="true" data-iconpos="notext" data-inline="true" data-icon="plus"></button><?php echo $this->translate('Press plus to add an event')?></li>
        <li><?php echo $this->translate('Efficient saving though learning application and gps based propositions')?></li>
        <li><?php echo $this->translate('Save the key characteristics of your events in each category')?></li>
        <li><?php echo $this->translate('To save: press the plus button first choose a category; then press the plus button')?></li>
    </ul>
    
    <h2 class="title-function"><?php echo $this->translate('Categorize')?></h2>
    <ul data-role="listview" data-inset="true">
        <li><button data-mini="true" data-theme="b" data-corners="true" data-inline="true" ><?php echo $this->translate('button_categories')?></button><?php echo $this->translate('Choose a category to access specific tools')?></li>
        <li><?php echo $this->translate('Every category has its own tool box')?></li>
        <li><?php echo $this->translate('You only use your favorite categories')?></li>
    </ul>
    
    <h2 class="title-function"><?php echo $this->translate('Find')?></h2>
    <ul data-role="listview" data-inset="true">
        <li><?php echo $this->translate('Searching is easy with the categories')?></li>
        <li><?php echo $this->translate('Tags makes your search easier')?></li>
    </ul>
</div>