<h1><?php echo $this->translate('Welcome to Mylife'); ?></h1>
<p><?php echo $this->translate('you want to add a new event, press the plus button'); ?></p>
<p><?php echo $this->translate('you want to choose a category, press the categories button'); ?></p>
<p><?php echo $this->translate('you want to visualize Yourlife : go to the calendar / graph page within a category or from the starting page'); ?></p>