<?php echo $this->doctype() ?>
<html>
    <head>
        <?php echo $this->partial('partial/_head.phtml');?>
    </head>
    <body> 
        <nav id="upper-menu" class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <?php echo $this->listCategories('partial/_navDropdown.phtml','user'); 
                          if (($this->member()->role === 'admin') || ($this->member()->role === 'owner')) : echo $this->listCategories('partial/_navDropdown.phtml','backend'); endif;?>
                </div>
            </div>
        </nav>
        <div class="container-fluid">
            <div class="row-fluid">
                <div id="side-menu" class="span3">
                    <div class="row-fluid">
                        <?php echo $this->partial('partial/_vNav.phtml') ?>
                    </div>
                    <?php echo $this->buttonNewEvent(); ?>
                    <div class="row-fluid">   
                        <div id="calendar-events" class="pull-right">
                            <div id="calendarBiMonth"></div>
                        </div>
                    </div>
                </div>
                <div class="span8">
                    <?php echo $this->flashMessages();?>
                    <?php echo $this->layout()->content ; ?>
                </div>
            </div>
            <footer class="footer">
                <?php echo $this->partial('partial/_footer.phtml'); ?>
            </footer>
        </div>
        <?php echo $this->inlineScript(); ?>
    </body>
</html>
                