<?php echo $this->doctype()."\n" ?>
<html>
    <head>
        <?php echo $this->partial('partial/_head.phtml') ?>
    </head>
    <body> 
        <header id="homeheader" class="jumbotron subhead">
            <div class="container">
                <h1><?php echo $this->translate('title_sitename'); ?></h1>
                <p class="lead"><?php echo $this->translate('site_shortpres'); ?></p>
            </div>
        </header>
        <nav id="upper-menu" class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <?php echo $this->listCategories('partial/_navDropdown.phtml','user');
                      if ($this->member()->role === ('admin' || 'owner')) : echo $this->listCategories('partial/_navDropdown.phtml','backend'); endif;?>
            </div>
        </nav>
        <div class="container-fluid">
            <div class="row-fluid">
                <div id="side-menu" class="span3 bs-docs-sidebar">
                    <?php echo $this->partial('partial/_vNav.phtml') ?> 
                </div>
                <div id="main" class="span9">
                    <?php echo $this->flashMessages();?>
                    <?php echo $this->layout()->content ;?>
                </div>
             </div>
        </div>
        <footer class="footer">
            <div class="container-fluid">
                <?php echo $this->partial('partial/_footer.phtml') ?>
            </div>
        </footer>
        <?php echo $this->inlineScript(); ?>
    </body>
</html>

 

