<?php 
$this->headLink()->prependStylesheet('/css/lib/datebox.css');
$this->headScript()->offsetSetFile(100,'https://www.google.com/jsapi'); 
$this->headScript()->offsetSetFile(101,'/js/lib/jqm-datebox/datebox-core.js');
$this->headScript()->offsetSetFile(102,'/js/lib/jqm-datebox/datebox-core-modeCalbox.js');

if ($this->events)
{
    echo $this->subPageIndex($this->category,'last-events-page',[
        'content'   => $this->partial(
            'partial/_pageLastEvents-mobile.phtml',
            ['events' => $this->events,'all'=>$this->allOption]
        ),
        'active'    => 'page',
    ]);
    
    echo $this->subPageIndex($this->category,'calendar-page',[
        'content'   => $this->partial(
            'partial/_pageCalendar-mobile.phtml',
            ['events' => $this->events,'eventsPerDay' => $this->eventsPerDay]
        ),
        'active'    => 'calendar',
    ]);
    
    echo $this->subPagesGraphIndex($this->category,$this->graphs($this->events,$this->allOption));
    
} 
else //if no event to show
{
    echo $this->subPageIndex($this->category,'last-events-page',[
        'content'   => $this->partial('partial/_welcome.phtml'),
        'active'    => 'page',
        'title'     => ucfirst($this->translate('msg_welcome')),
    ]);
}
    echo $this->subPageIndex($this->category,'list_singleCategories',[
        'content'   => $this->listCategories('partial/_categoriesNewEventMenu.phtml','eventAdd'),
        'title'     => ucfirst($this->translate('menu_add_event'))
    ]);
    
    echo $this->subPageIndex($this->category,'list_allCategories',[
        'content'   => $this->listCategories('partial/_categoriesMenu.phtml','metaCategory'),
        'title'     => ucfirst($this->translate('menu_see_categories')),
        'buttonLeft' => $this->htmlMobileButtonNavBar(['type' => 
            Pepit_View_Helper_HtmlMobileButtonNavBar::TYPE_BUTTON_BACK]),
    ]);
    
    echo $this->subPageIndex($this->category,'options-page',[
        'content'   => $this->settingsMobile(),
        'title'     => ucfirst($this->translate('menu_settings')),
        'active'    => 'options'
    ]);
    
?>
     
    <span id="dataToClientSide" data-categoryId="<?php echo $this->category->id; ?>"></span>

