<?php 
$this->headLink()->prependStylesheet('/css/lib/datebox.css');
$this->headScript()->offsetSetFile(100,'https://www.google.com/jsapi'); 
$this->headScript()->offsetSetFile(101,'/js/lib/jqm-datebox/datebox-core.js');
$this->headScript()->offsetSetFile(102,'/js/lib/jqm-datebox/datebox-core-modeCalbox.js');

$this->inlineScript()->offsetSetFile(40,'/js/lib/underscore.js');
$this->inlineScript()->offsetSetFile(50,'/js/lib/backbone.js');

$this->inlineScript()->offsetSetFile(150,'/js/mvc/views/eventListView.js');
$this->inlineScript()->offsetSetFile(180,'/js/mvc/views/indexView.js');
$this->inlineScript()->offsetSetFile(152,'/js/mvc/views/propertyView.js');
$this->inlineScript()->offsetSetFile(160,'/js/mvc/views/calendarView.js');
$this->inlineScript()->offsetSetFile(153,'/js/mvc/views/eventListItemView.js');
$this->inlineScript()->offsetSetFile(157,'/js/mvc/views/pageView.js');
$this->inlineScript()->offsetSetFile(159,'/js/mvc/views/eventView.js');
$this->inlineScript()->offsetSetFile(154,'/js/mvc/models/event.js');
$this->inlineScript()->offsetSetFile(155,'/js/mvc/models/events.js');
$this->inlineScript()->offsetSetFile(158,'/js/mvc/models/pages.js');
$this->inlineScript()->offsetSetFile(156,'/js/mvc/models/page.js');
$this->inlineScript()->offsetSetFile(149,'/js/mvc/utils/close.js');


if ($this->events)
{
    echo $this->subPageIndex($this->category,'last-events-page',[
        'content'   => $this->partial(
            'partial/_pageLastEvents-mobile.phtml',
            ['events' => $this->events,'all'=>$this->allOption]
        ),
        'active'    => 'last-events',
    ]);
    
    echo $this->subPageIndex($this->category,'calendar-page',[
        'content'   => $this->partial(
            'partial/_pageCalendar-mobile.phtml',
            ['events' => $this->events,'eventsPerDay' => $this->eventsPerDay]
        ),
        'active'    => 'calendar',
    ]);
    
    echo $this->subPagesGraphIndex($this->category,$this->graphs($this->events,$this->allOption));
    
} 
else //if no event to show
{
    echo $this->subPageIndex($this->category,'last-events-page',[
        'content'   => $this->partial('partial/_welcome.phtml'),
        'active'    => 'last-events',
        'title'     => ucfirst($this->translate('msg_welcome')),
        'popups'    => [
                    ['attribs' => ['id' => 'bla'],'content' => 'bla']
        ]
    ]);
    
    
    
    
}
    echo $this->subPageIndex($this->category,'list_singleCategories',[
        'content'   => $this->listCategories('partial/_categoriesNewEventMenu.phtml','eventAdd'),
        'title'     => ucfirst($this->translate('menu_add_event'))
    ]);
    
    echo $this->subPageIndex($this->category,'list_allCategories',[
        'content'   => $this->listCategories('partial/_categoriesMenu.phtml','metaCategory'),
        'title'     => ucfirst($this->translate('menu_see_categories')),
        'buttonLeft' => $this->htmlMobileButtonNavBar(['type' => 
            Pepit_View_Helper_HtmlMobileButtonNavBar::TYPE_BUTTON_BACK],[],
                ucfirst($this->translate('menu_back_to_previous_page'))),
    ]);
    
    echo $this->subPageIndex($this->category,'options-page',[
        'content'   => $this->settingsMobile(),
        'title'     => ucfirst($this->translate('menu_settings')),
        'active'    => 'options',
        'buttonRight' => '',
    ]);
    
?>
     
    <span id="dataToClientSide" data-categoryId="<?php echo $this->category->id; ?>"></span>
    <?php $this->inlineScript()->setAllowArbitraryAttributes('true')->captureStart('append','text/template',['noescape'=>'true','id' => 'last-events-page-template']);
        echo $this->subPageIndex($this->category,'<%= id %>',[
            'content'       => '',
            'title'         => '<%= title %>',
            'active'        => 'graphs',
            'buttonRight'   => '',
            'noWrap'        => true
        ]);
        $this->inlineScript()->captureEnd()?>
    <?php $this->inlineScript()->setAllowArbitraryAttributes('true')->captureStart('append','text/template',['noescape'=>'true','id' => 'event-line-template'])?>
        <a data-ajax="false" class="event-line-link" href="<%= href %>" data-eventId="<%= eventId %>">
            <img  src="<%= imgSrc %>" />
            <h4><%= title %></h4>
            <p>
                <strong><%= commonProperties %></strong>
            </p>
            <p>
                <%= specificProperties %>
            </p>
            <p class="ui-li-aside"><strong><%= aside %></strong></p>  
        </a>
    <?php $this->inlineScript()->captureEnd()?>
    <?php $this->inlineScript()->setAllowArbitraryAttributes('true')->captureStart('append','text/template',['noescape'=>'true','id' => 'event-property-template'])?>
        <img src="/images/icons/nav_bar/<%= srcIcon %>" style="width:15px;height:15px;"/><%= content %>
    <?php 
        $this->inlineScript()->captureEnd();   
        
        //capture template for single event view
        $this->inlineScript()->setAllowArbitraryAttributes('true')
                               ->captureStart('append','text/template',[
                                   'noescape'=>'true',
                                   'id' => 'event-details-template'
        ]);
        echo $this->partial('partial/_showEventContent-mobile.phtml',[
            'eventId'               => '<%= eventId %>',           
            'categoryId'            => '<%= categoryId %>',
            'date'                  => '<%= date %>',
            'userImage'             => '<%= userImage %>',
            'commonProperties'      => '<%= commonProperties %>',
            'specificProperties'    => '<%= specificProperties %>',
        ]);
        $this->inlineScript()->captureEnd();
        
        //capture template for the delete popup of the single event view
        $this->inlineScript()->setAllowArbitraryAttributes('true')
                             ->captureStart('append','text/template',[
                                 'noescape' =>'true',
                                 'id'       => 'event-deletePopup-template'
        ]);
        echo $this->partial('partial/_showEventPopup-mobile.phtml',[
            'eventId' => '<%= eventId %>' ,           
            'categoryId' => '<%= categoryId %>'            
        ]);
        $this->inlineScript()->captureEnd();    