<div data-role="page"> 
    <div data-role="header">...</div> 
    <div data-role="content">
        <div id="upper-block" class="row-block ui-grid-b">
            <div id="date-category" class="ui-block-a">
                <div class="inside">
                    <?php echo $this->event->category->name; ?>
                    <?php echo $this->event->date->format('m'); ?> / <?php echo $this->event->date->format('d'); ?>
                </div>
            </div>
            <div id="photo" class="ui-block-b">
                <div class="inside">ytryr</div>
            </div>
            <div id="photo" class="ui-block-c">
                <div class="inside">ytryr</div>
            </div>
        </div>
        <div id="items-central-block" class="row-block">
            <?php echo (new Events_View_Helper_EventLine($this->event))->renderSpecificProperties($this->event);?>
        </div>
        <div id="buttons-lower-block" class="row-block ui-grid-a">
            <div class="ui-block-a">
                <div class="ui-grid-b">
                    <div class="ui-block-a"></div>
                    <div class="ui-block-b">
                        <a data-role="button" data-theme="a" href="<?php echo $this->url(['action'=>'edit','containerRowId' => $this->event->id],'event');?>">
                        <?php echo ucfirst($this->translate('event_edit_button')); ?>
                        </a>
                    </div>
                    <div class="ui-block-c"></div>
                </div>
            </div>
            <div class="ui-block-b">
                <div class="ui-grid-b">
                    <div class="ui-block-a"></div>
                    <div class="ui-block-b">
                        <a data-role="button" data-theme="a" href="<?php echo $this->url(['action'=>'delete','containerRowId' => $this->event->id],'event'); ?>">
                            <?php echo ucfirst($this->translate('event_delete_button')); ?>
                        </a>
                    </div>
                    <div class="ui-block-c"></div>
                </div>
            </div>
        </div>
    </div>
    
</div>
