<?php $this->inlineScript()->offsetSetFile(150,'/js/lib/camera-mobile-plugin/jquery-easing.js'); ?>
<?php $this->inlineScript()->offsetSetFile(151,'/js/lib/camera-mobile-plugin/camera.js'); ?>
<?php $this->headLink()->prependStylesheet('/css/camera.css'); ?>
<?php $this->headLink()->headlink(['rel' => "apple-touch-startup-image",'href' => "/images/startup.png"],'APPEND'); ?>
<div data-role="page">
    <div data-role="content">
        <div class=".fluid_container" id="slide-show">            
            <div class="camera_wrap camera_azure_skin" id="camera_wrap_1">
                <?php echo $this->slide('/images/images-camera/slides/road.jpg',"camera_caption",
                        $this->translate('Save, remember and enjoy')) ;?>
                <?php echo $this->slide('/images/images-camera/slides/railway.jpg',"camera_caption",
                        $this->translate('Keep quick and in each categories')) ;?>
                <?php echo $this->slide('/images/images-camera/slides/bridge.jpg',"camera_caption",
                        $this->translate('One environment for one category')); ?>
                <?php echo $this->slide('/images/images-camera/slides/agenda.jpg',"camera_caption",
                        $this->translate('Find your past immediatly back')); ?>
                <?php echo $this->slide('/images/images-camera/slides/world.jpg',"camera_caption",
                        $this->translate('Visualize and enjoy'));?>
            </div><!-- #camera_wrap_1 -->
            <div class="ui-grid-a" id="button-choice-block">
                <div class="ui-block-a">
                    <a <?php echo $this->dataPrefetch() ?> class="button-choice" data-role="button" href="<?php echo $this->url(['action'=>'login'],'access'); ?>" data-transition="none" data-theme="b">
                       <?php echo $this->translate('menu_connect')?>
                    </a>
                </div>
                <div class="ui-block-b">
                    <a <?php echo $this->dataPrefetch() ?> class="button-choice" data-role="button" href="<?php echo $this->url(['action'=>'register'],'member'); ?>" data-transition="none" data-theme="b">
                       <?php echo $this->translate('menu_signup')?>
                    </a>
                </div>	   
            </div>
        </div><!-- .fluid_container -->
    </div>
</div>