<div id="front-welcome" class="front-welcome-text">
    <h1>
        <?php echo $this->translate('title_sitename'); ?>
        <img class="logo-site" src="/images/logo-site.png"/></h1>
    <h4><?php echo $this->translate('site_slogan'); ?></h4>
    <p><?php echo $this->translate('site_shortpres'); ?> </p>
</div>
<div class="row-fluid">
    <div class="span5">
<?php echo $this->formLogin; ?>       
    </div>
    <div class="span6 offset1">
<?php echo $this->formRegister; ?>
    </div>
</div>
<img id='image-access' class="imageobject" src="/images/background-access<?php echo rand(1,4);?>.jpg"/>


