<?php echo $this->partial('partial/_mobilePage.phtml', array(
    'id'         => 'connect',
    'content'    => ($this->formLogin) ? $this->formLogin : '',
    'title'      => ucfirst($this->translate('title_sitename')),
    'buttonLeft' => '<a '.$this->dataPrefetch().' href="'.$this->url([],'home').'" data-ajax="false" data-theme="b" data-transition="flip" class="ui-btn-left">'.$this->translate('menu_home').'</a>',
    'buttonRight'=> '<a '.$this->dataPrefetch().' href="'.$this->url(['action' => 'register'],'member').'" data-theme="b" data-transition="slide" class="ui-btn-right">'.$this->translate('msg_question_become_member').'</a>',
    'footer'     => false
)); ?>